export default {
    wrapper: {
        position: 'fixed',
        zIndex: 99998,
        top: 0,
        bottom: 0,
        right: 0,
        left: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modal: {
        position: 'relative',
        zIndex: 99999,
        background: 'white',
        boxSizing: 'borderBox',
        border: '1px solid grey',
        borderRadius: 3,
        height: '90%',
        width: '90%',
        maxWidth: ({ maxWidth, fluid }) => !fluid && maxWidth,
        minWidth: ({ minWidth, fluid }) => !fluid && minWidth,
        maxHeight: ({ maxHeight, fluid }) => !fluid && maxHeight,
        minHeight: ({ minHeight }) => minHeight,
        display: 'flex',
        flexDirection: 'column',
        flexWrap: 'nowrap',
    },
};
